#!/bin/bash

echo "🔍 GUIDE : Trouver l'URL PostgreSQL Supabase"
echo "============================================"
echo ""
echo "1. Ouvrir dans votre navigateur :"
echo "   https://app.supabase.com/project/sigjxcnrthaxoceclmdi/settings/database"
echo ""
echo "2. Chercher la section 'Connection string'"
echo ""
echo "3. Copier l'URL 'URI' qui ressemble à :"
echo "   postgresql://postgres.sigjxcnrthaxoceclmdi:[PASSWORD]@aws-0-eu-west-1.pooler.supabase.com:6543/postgres"
echo ""
echo "4. Remplacer [PASSWORD] par votre mot de passe Supabase"
echo ""
echo "5. Mettre à jour .env.production avec cette URL complète"
echo ""
echo "6. Tester avec : npm run test:supabase"
echo ""
echo "💡 L'URL doit commencer par 'postgresql://' et non 'https://'"
